spring:
  datasource:
    url: jdbc:mysql://192.168.159.130:3306/houses?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  freemarker:
    charset: utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
