spring:
  datasource:
    url: jdbc:mysql://192.168.159.130:3306/houses?useUnicode=true&amp;amp;characterEncoding=UTF-8&amp;amp;zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
     
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml